name: Toot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  tweet:
    name: Toot
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v3

      - id: install
        name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: 3.8

      - id: execute
        name: Execute Jupyter notebook
        run: pipenv run jupyter execute tweet.ipynb
        shell: bash
        env:
          MASTODON_CLIENT_KEY: ${{ secrets.MASTODON_CLIENT_KEY }}
          MASTODON_CLIENT_SECRET: ${{ secrets.MASTODON_CLIENT_SECRET }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

      - run: date > datestamp.txt

      - id: commit
        name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git pull origin $GITHUB_REF
          git add datestamp.txt
          git commit -m "Ran a scrape" --author="palewire <palewire@users.noreply.github.com>" && git push || true
        shell: bash
